### PR TITLE
Make it better

### PR DESCRIPTION
**Pull request by MarcelBolten**

### CODE REVIEW

**Comment by NicolasCARPi** [comment]
Had to remove the .npmrc to publish, but thanks, it's better now :+1:

**Comment by MarcelBolten** [comment]
Interesting, for me it worked with the .npmrc file.
However, great that it works better now.

**Comment by NicolasCARPi** [comment]
It might be because I have 2FA activated, or because the package is scoped.

**Comment by MarcelBolten** [comment]
I tried it with a scoped package and it worked, so it is 2FA I think.

**Pull request merged**
